spring:
  application:
    name: gateway-server
  config:
    import: configserver:http://localhost:8071
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include:
          - env
          - mappings
          - gateway